export const INVALID_KEYS = [
	'F1',
	'F2',
	'F3',
	'F4',
	'F5',
	'F6',
	'F7',
	'F8',
	'F9',
	'F10',
	'F11',
	'F12',
	'PrintScreen',
	'Delete',
	'Escape',
	'PageUp',
	'PageDown',
	'Home',
	'End',
	'ArrowUp',
	'ArrowDown',
	'ArrowLeft',
	'ArrowRight',
	'Shift',
	'Alt',
	'Enter',
	'Control',
	'CapsLock',
	'Meta',
	'Tab',
];

export const VOWEL_TO_ACCENT: Record<string, string> = { 'a': 'á', 'e': 'é', 'i': 'í', 'o': 'ó', 'u': 'ú', 'ü': 'u', 'A': 'Á', 'E': 'É', 'I': 'Í', 'O': 'Ó', 'U': 'Ú', 'Ü': 'U' }